### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'get'

### ISSUE THREAD

**Issue by karolzak** [Azure-Samples/cognitive-service-vision-model-customization-python-samples#15]
Running into error caused by line 52 in `client.py`
https://github.com/Azure-Samples/cognitive-service-vision-model-customization-python-samples/blame/a04187b0685ec65c5d855a4f062352bb77ec66ab/cognitive_service_vision_model_customization_python_samples/clients/client.py#L52

Full error message:
```
Traceback (most recent call last):

  File "data_description_pipeline.py", line 363, in <module>

    main()

  File "data_description_pipeline.py", line 342, in main

    data_descr.process_files()

  File "data_description_pipeline.py", line 91, in process_files

    json_not_found, article_not_found = self.process_png_files(index, each_article, each_img, self.data_source, self.precutter_infos)

  File "data_description_pipeline.py", line 161, in process_png_files

    florence_json = {"Florence": florence_predict(model_name="retrained_fv_model", img_bytes=image_binary)}

  File "/mnt/azureml/cr/j/9f9ba4a2d969495f8b55d6a5322752de/exe/wd/florence.py", line 45, in florence_predict

    prediction_json = prediction_client.predict(model_name, img_bytes)

  File "/azureml-envs/azureml_b994edb6f763297b6f48a202666a94e8/lib/python3.8/site-packages/cognitive_service_vision_model_customization_python_samples/clients/prediction_client.py", line 6, in predict

    return self.request_post('imageanalysis:analyze', params={'model-name': model_name}, data=img, content_type=content_type)

  File "/azureml-envs/azureml_b994edb6f763297b6f48a202666a94e8/lib/python3.8/site-packages/cognitive_service_vision_model_customization_python_samples/clients/client.py", line 53, in request_post

    if r.get(headers['Content-Type'], None) == 'image/jpeg':

AttributeError: 'Response' object has no attribute 'get'
```

**Comment by karolzak** [comment]
Seems like there's an open PR #17 which supposed to fix this issue.

**Comment by lucas95123** [comment]
@karolzak yes, please take a look and see if this resolve the error
